[package]
name = "loose_string"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha256 = "1.1.2"

[lib]
name = "libra"
path = "src/lib.rs"
